In [106]:
%matplotlib widget
import numpy as np
import matplotlib
print(matplotlib.__version__)
import matplotlib.pyplot as plt

3.1.2


In [107]:
arr = np.tile(np.arange(13),10).reshape(10,13)

In [108]:
arr[:,0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [109]:
fig,  axes = plt.subplots(ncols=2, nrows=2, figsize=(9,3), 
                               gridspec_kw={'width_ratios':[1,2]})
im = axes[0,0].imshow(arr, origin='lower')
_ = axes[0,1].plot(arr) #rows are observations, columns variables
for i, row in enumerate(arr):
    _ = axes[1,0].bar(np.arange(row.shape[0]) + (i/arr.shape[0]), row, 
                      width=(1/(arr.shape[0]))) 
    
bottom = np.zeros(row.shape)
for i, row in enumerate(arr):
    _ = axes[1,1].bar(np.arange(row.shape[0]), row, bottom=bottom)
    bottom+=row
    print(bottom)
    
fig.colorbar(im, ax=ax1, fraction=.035)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24.]
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36.]
[ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.]
[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72.]
[ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63. 70. 77. 84.]
[ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72. 80. 88. 96.]
[  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.  99. 108.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120.]


In [110]:
%reload_ext autoreload
%autoreload 2

In [111]:
import darray

In [113]:
dsa = darray.DataSourceArray(arr)

In [52]:
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(9,3),
                               sharex=True, sharey=True,
                             gridspec_kw={'width_ratios':[1,2]})
im = darray.ArrayImage(ax1, dsa)
ax1.add_image(im) #inside imshow
ax1.set_aspect('equal') #inside imshow
line = darray.ArrayLine(dsa)
ax2.add_artist(line)
ax2.set_xlim(-.5,14)
ax2.set_ylim(-.5,12)

fig.colorbar(im, ax=ax1, fraction=.045)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [55]:
dsa.data = arr.T
np.random.shuffle(dsa.data)
fig.canvas.draw_idle()

In [115]:
import matplotlib.axes as maxes

Signature:
maxes.Axes.bar(
    self,
    x,
    height,
    width=0.8,
    bottom=None,
    *,
    align='center',
    data=None,
    **kwargs,
)
Docstring:
Make a bar plot.

The bars are positioned at *x* with the given *align*\ment. Their
dimensions are given by *width* and *height*. The vertical baseline
is *bottom* (default 0).

Each of *x*, *height*, *width*, and *bottom* may either be a scalar
applying to all bars, or it may be a sequence of length N providing a
separate value for each bar.

Parameters
----------
x : sequence of scalars
    The x coordinates of the bars. See also *align* for the
    alignment of the bars to the coordinates.

height : scalar or sequence of scalars
    The height(s) of the bars.

width : scalar or array-like, optional
    The width(s) of the bars (default: 0.8).

bottom : scalar or array-like, optional
    The y coordinate(s) of the bars bases (default: 0).

align : {'center', 'edge'}, optional, default: 'center'
    Alignment of the bars to the *x