In [1]:
%matplotlib widget
import numpy as np
import matplotlib
print(matplotlib.__version__)
import matplotlib.pyplot as plt

3.1.2


In [2]:
arr = np.tile(np.arange(13),10).reshape(10,13)

In [5]:
fig,  axes = plt.subplots(ncols=2, nrows=2, figsize=(9,3), 
                               gridspec_kw={'width_ratios':[1,2]})
im = axes[0,0].imshow(arr, origin='lower')
_ = axes[0,1].plot(arr) #rows are observations, columns variables
for i, row in enumerate(arr):
    _ = axes[1,0].bar(np.arange(row.shape[0]) + (i/arr.shape[0]), row, 
                      width=(1/(arr.shape[0]))) 
    
bottom = np.zeros(row.shape)
for i, row in enumerate(arr):
    _ = axes[1,1].bar(np.arange(row.shape[0]), row, bottom=bottom)
    bottom+=row
    print(bottom)
    
fig.colorbar(im, ax=axes[0,0], fraction=.035)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24.]
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36.]
[ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.]
[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72.]
[ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63. 70. 77. 84.]
[ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72. 80. 88. 96.]
[  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.  99. 108.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120.]


In [6]:
%reload_ext autoreload
%autoreload 2

In [7]:
plt.close('all')

In [8]:
import darray

In [9]:
dsa = darray.DataSourceArray(arr)

In [11]:
plt.close('all')
fig,  axes = plt.subplots(ncols=2, nrows=2, figsize=(9,3), 
                               gridspec_kw={'width_ratios':[1,2]})
im = darray.ArrayImage(axes[0,0], dsa)
axes[0,0].add_image(im) #inside imshow
axes[0,0].set_aspect('equal') #inside imshow
line = darray.ArrayLine(dsa)
axes[0,1].add_artist(line)

axes[0,1].set_xlim(-.5,14)
axes[0,1].set_ylim(-.5,12)

#bars = darray.ArrayBar(dsa)
#axes[1,0].add_artist(bars)
fig.colorbar(im, ax=axes[0,0], fraction=.045)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [14]:
dsa.data = arr.T
np.random.shuffle(dsa.data)
fig.canvas.draw_idle()

In [ ]:
plt.close('all')

In [141]:
q = dsa.projectLine2D(None)

In [149]:
[np.vstack([x,y]).T for x,y in zip(q.x, q.y)]

[array([[0, 0],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0],
        [5, 0],
        [6, 0],
        [7, 0],
        [8, 0],
        [9, 0]]), array([[0, 1],
        [1, 1],
        [2, 1],
        [3, 1],
        [4, 1],
        [5, 1],
        [6, 1],
        [7, 1],
        [8, 1],
        [9, 1]]), array([[0, 2],
        [1, 2],
        [2, 2],
        [3, 2],
        [4, 2],
        [5, 2],
        [6, 2],
        [7, 2],
        [8, 2],
        [9, 2]]), array([[0, 3],
        [1, 3],
        [2, 3],
        [3, 3],
        [4, 3],
        [5, 3],
        [6, 3],
        [7, 3],
        [8, 3],
        [9, 3]]), array([[0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [9, 4]]), array([[0, 5],
        [1, 5],
        [2, 5],
        [3, 5],
        [4, 5],
        [5, 5],
        [6, 5],
        [7, 5],
        [8, 5],
        [9, 5]]), array([[0, 6],
        [1, 6],
  